### ISSUE TITLE
just signed up for DeepL and made a new Open AI api key, returning this error with recording

### ISSUE THREAD

**Issue by enlargedhousecats** [Sound932/AIVoice#1]
![image](https://github.com/user-attachments/assets/fefcef64-59bd-4f35-9798-d4119790887a)

**Comment by enlargedhousecats** [comment]
I have also reinstalled .net 6.0
currently using windows 11

**Comment by Ameer5121** [comment]
Hi, add me on discord, I'll help you. Your open AI key probably does not have any usage.  discord id: sound9535

**Comment by enlargedhousecats** [comment]
will do
